#include "sshworkspace.h"
#include "settings/diagnostics.h"
#include "git/gitclient.h"
#include "diff/diffwidget.h"
#include "history/historytable.h"
#include <QCloseEvent>
#include <QComboBox>
#include <QFileDialog>
#include <QFileInfo>
#include <QFormLayout>
#include <QHeaderView>
#include <QInputDialog>
#include <QJsonArray>
#include <QJsonDocument>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QMessageBox>
#include <QPlainTextEdit>
#include <QPushButton>
#include <QSettings>
#include <QSpinBox>
#include <QSplitter>
#include <QTextDocument>
#include <QVBoxLayout>
#include <QUuid>
#include <QDateTime>
#include <QRegularExpression>

namespace {
bool confirm(QWidget *parent,const QString &title,const QString &message){QMessageBox box(QMessageBox::Warning,title,message,QMessageBox::Yes|QMessageBox::No,parent,Qt::Dialog|Qt::WindowTitleHint|Qt::WindowCloseButtonHint);box.setDefaultButton(QMessageBox::No);return box.exec()==QMessageBox::Yes;}
QJsonArray savedArray(const char *key){return QJsonDocument::fromJson(QSettings().value(key).toByteArray()).array();}
void saveArray(const char *key,const QJsonArray &array){QSettings().setValue(key,QJsonDocument(array).toJson(QJsonDocument::Compact));}
}
SshWorkspace::SshWorkspace(QWidget *parent,const QString &storage):QDialog(parent,Qt::Dialog|Qt::WindowTitleHint|Qt::WindowCloseButtonHint),executor_(this,storage){
    setObjectName("sshWorkspace");resize(1400,900);setMinimumSize(1050,720);
    auto *layout=new QVBoxLayout(this);scope_=new QLabel(tr("SSH 원격 작업공간 · 연결되지 않음"));scope_->setTextFormat(Qt::PlainText);scope_->setWordWrap(true);layout->addWidget(scope_);
    auto *help=new QLabel(tr("이 창의 Git과 파일 작업은 선택한 원격 컴퓨터에서 실행됩니다. 로컬 GitHub 로그인은 전달하지 않습니다. POSIX 서버에 Python 3와 Git 2.31 이상이 필요합니다."));help->setWordWrap(true);layout->addWidget(help);
    auto *split=new QSplitter;layout->addWidget(split,1);auto *left=new QWidget;auto *side=new QVBoxLayout(left);side->setContentsMargins(0,0,8,0);split->addWidget(left);
    profiles_=new QComboBox;profiles_->setObjectName("sshProfiles");side->addWidget(profiles_);
    auto *form=new QFormLayout;side->addLayout(form);
    auto field=[&](const QString &label,const char *id){auto *w=new QLineEdit;w->setObjectName(id);form->addRow(label,w);controls_.append(w);return w;};
    alias_=field(tr("표시 이름"),"sshAlias");host_=field(tr("호스트 / IP"),"sshHost");user_=field(tr("SSH OS 사용자"),"sshUser");
    port_=new QSpinBox;port_->setObjectName("sshPort");port_->setRange(1,65535);port_->setValue(22);form->addRow(tr("포트"),port_);controls_.append(port_);
    key_=field(tr("개인키 경로 · 비우면 agent/기본키"),"sshIdentity");root_=field(tr("허용할 원격 시작 경로"),"sshRoot");root_->setText("/home");
    qobject_cast<QLabel*>(form->labelForField(key_))->setText(tr("개인키 경로"));key_->setToolTip(tr("개인키 경로 · 비우면 agent/기본키"));qobject_cast<QLabel*>(form->labelForField(root_))->setText(tr("시작 경로"));root_->setToolTip(tr("허용할 원격 시작 경로"));
    auto *profileRow=new QHBoxLayout;side->addLayout(profileRow);auto *save=new QPushButton(tr("프로필 저장"));save->setObjectName("saveSshProfile");profileRow->addWidget(save);controls_.append(save);connect(save,&QPushButton::clicked,this,&SshWorkspace::saveProfile);
    auto *remove=new QPushButton(tr("프로필 제거"));profileRow->addWidget(remove);controls_.append(remove);connect(remove,&QPushButton::clicked,this,[this]{if(!confirm(this,tr("SSH 프로필 제거"),tr("프로필과 원격 저장소 목록 등록만 제거합니다. 원격 파일과 호스트 키 파일은 유지합니다.")))return;auto all=savedArray("ssh/profiles");for(int i=all.size()-1;i>=0;--i)if(all[i].toObject().value("id")==profile().id)all.removeAt(i);saveArray("ssh/profiles",all);auto repos=savedArray("ssh/repositories");for(int i=repos.size()-1;i>=0;--i)if(repos[i].toObject().value("profile")==profile().id)repos.removeAt(i);saveArray("ssh/repositories",repos);loadProfiles();});
    connect_=new QPushButton(tr("호스트 확인 · 연결 / 재연결"));connect_->setObjectName("connectSsh");side->addWidget(connect_);controls_.append(connect_);connect(connect_,&QPushButton::clicked,this,&SshWorkspace::connectHost);
    side->addWidget(new QLabel(tr("SSH 저장소 · 더블 클릭으로 열기")));saved_=new QListWidget;saved_->setObjectName("sshRepositories");side->addWidget(saved_,1);controls_.append(saved_);
    connect(saved_,&QListWidget::itemDoubleClicked,this,[this](QListWidgetItem *item){if(!discardDraft())return;path_->setText(item->data(Qt::UserRole).toJsonObject().value("path").toString());refresh();});
    auto *favorite=new QPushButton(tr("저장소 즐겨찾기 전환"));side->addWidget(favorite);controls_.append(favorite);connect(favorite,&QPushButton::clicked,this,[this]{remember(true);});
    folders_=new QListWidget;folders_->setObjectName("sshFolders");side->addWidget(folders_,1);controls_.append(folders_);connect(folders_,&QListWidget::itemDoubleClicked,this,[this](QListWidgetItem *item){if(!discardDraft())return;path_->setText(item->data(Qt::UserRole).toString());browse();});
    auto *right=new QWidget;auto *body=new QVBoxLayout(right);body->setContentsMargins(8,0,0,0);split->addWidget(right);split->setSizes({300,1060});
    auto *pathRow=new QHBoxLayout;path_=new QLineEdit;path_->setObjectName("sshRepositoryPath");path_->setPlaceholderText(tr("원격 저장소의 절대 경로"));pathRow->addWidget(path_,1);controls_.append(path_);auto *browseButton=new QPushButton(tr("폴더 탐색"));pathRow->addWidget(browseButton);controls_.append(browseButton);connect(browseButton,&QPushButton::clicked,this,&SshWorkspace::browse);
    refresh_=new QPushButton(tr("저장소 열기 · 상태 재확인"));refresh_->setObjectName("refreshSshRepository");pathRow->addWidget(refresh_);controls_.append(refresh_);connect(refresh_,&QPushButton::clicked,this,[this]{if(discardDraft())refresh();});body->addLayout(pathRow);
    branches_=new QComboBox;branches_->setObjectName("sshBranches");body->addWidget(branches_);controls_.append(branches_);
    connect(branches_,&QComboBox::activated,this,[this]{if(branches_->currentText()!=state_.value("branch").toString())mutate("switch",{{"branch",branches_->currentText()}});});
    auto *actions=new QHBoxLayout;body->addLayout(actions);
    auto writeButton=[&](const QString &label,const char *action){auto *b=new QPushButton(label);b->setObjectName("ssh_"+QString(action));actions->addWidget(b);writes_.append(b);connect(b,&QPushButton::clicked,this,[this,action]{mutate(action);});return b;};
    writeButton(tr("체크 파일 Stage"),"stage");writeButton(tr("체크 파일 Unstage"),"unstage");writeButton(tr("Fetch · 원격 서버 정보 받기"),"fetch");
    auto *syncButton=new QPushButton(tr("Fetch 결과 비교 · Pull / Push"));actions->addWidget(syncButton);writes_.append(syncButton);connect(syncButton,&QPushButton::clicked,this,[this]{if(fetchId_.isEmpty()){status_->setText(tr("이 SSH 연결에서 먼저 Fetch하세요."));return;}send({{"action","sync-info"}},[this](bool ok,const QJsonObject &value,const QString &){if(!ok)return;const auto behind=value.value("behind").toInt(),ahead=value.value("ahead").toInt();if(behind&&ahead){status_->setText(tr("원격 이력이 갈라졌습니다. 서버에서 병합·충돌 해결 후 다시 Fetch하세요."));return;}if(!behind&&!ahead){status_->setText(tr("Fetch 기준으로 최신 상태입니다."));return;}mutate(behind?"pull":"push",{{"fetch_id",fetchId_},{"upstream",value.value("upstream")}});});});
    auto *newBranch=new QPushButton(tr("새 브랜치"));actions->addWidget(newBranch);writes_.append(newBranch);connect(newBranch,&QPushButton::clicked,this,[this]{QInputDialog dialog(this,Qt::Dialog|Qt::WindowTitleHint|Qt::WindowCloseButtonHint);dialog.setLabelText(tr("현재 원격 브랜치에서 만들 새 이름"));if(dialog.exec()==QDialog::Accepted)mutate("branch",{{"branch",dialog.textValue()}});});
    auto *deleteBranch=new QPushButton(tr("현재 원격 브랜치 삭제"));body->addWidget(deleteBranch);writes_.append(deleteBranch);connect(deleteBranch,&QPushButton::clicked,this,[this]{QInputDialog dialog(this,Qt::Dialog|Qt::WindowTitleHint|Qt::WindowCloseButtonHint);dialog.setLabelText(tr("삭제 대상 서버 이름을 입력하세요: %1\nmain/master로 이동한 뒤 병합된 현재 브랜치만 삭제합니다. HEAD 복구 참조를 남깁니다.").arg(profile().host));if(dialog.exec()==QDialog::Accepted&&dialog.textValue()==profile().host)mutate("delete-branch");});
    auto *views=new QSplitter;body->addWidget(views,3);files_=new QListWidget;files_->setObjectName("sshFiles");views->addWidget(files_);controls_.append(files_);
    auto *content=new QWidget;auto *contentLayout=new QVBoxLayout(content);views->addWidget(content);views->setSizes({280,700});
    auto *viewActions=new QHBoxLayout;contentLayout->addLayout(viewActions);
    auto *diffButton=new QPushButton(tr("선택 파일 Diff"));viewActions->addWidget(diffButton);controls_.append(diffButton);connect(diffButton,&QPushButton::clicked,this,[this]{showFile(false);});
    auto *edit=new QPushButton(tr("원격 파일 편집"));viewActions->addWidget(edit);controls_.append(edit);connect(edit,&QPushButton::clicked,this,[this]{showFile(true);});
    auto *openFile=new QPushButton(tr("파일 경로로 열기"));viewActions->addWidget(openFile);controls_.append(openFile);connect(openFile,&QPushButton::clicked,this,[this]{if(state_.isEmpty()||!discardDraft())return;QInputDialog dialog(this,Qt::Dialog|Qt::WindowTitleHint|Qt::WindowCloseButtonHint);dialog.setLabelText(tr("원격 저장소 기준 상대 파일 경로"));if(dialog.exec()!=QDialog::Accepted||dialog.textValue().isEmpty())return;auto *item=new QListWidgetItem(dialog.textValue(),files_);item->setData(Qt::UserRole,QJsonObject{{"path",dialog.textValue()},{"status","  "}});item->setCheckState(Qt::Unchecked);files_->setCurrentItem(item);showFile(true);});
    saveFile_=new QPushButton(tr("원격 파일 저장 · 백업"));saveFile_->setObjectName("saveSshFile");viewActions->addWidget(saveFile_);connect(saveFile_,&QPushButton::clicked,this,[this]{auto bytes=editor_->toPlainText().toUtf8();if(editCrlf_)bytes.replace("\n","\r\n");if(editBom_)bytes.prepend(QByteArray::fromHex("efbbbf"));mutate("save",{{"path",editPath_},{"hash",editHash_},{"data",QString::fromLatin1(bytes.toBase64())}});});
    diff_=new DiffWidget(new GitClient(this));diff_->setPatchActionsVisible(false);contentLayout->addWidget(diff_,1);
    editor_=new QPlainTextEdit;editor_->setObjectName("sshFileEditor");editor_->setLineWrapMode(QPlainTextEdit::NoWrap);editor_->hide();contentLayout->addWidget(editor_,1);connect(editor_->document(),&QTextDocument::modificationChanged,this,&SshWorkspace::update);
    auto *commitRow=new QHBoxLayout;title_=new QLineEdit;title_->setObjectName("sshCommitTitle");title_->setPlaceholderText(tr("원격 커밋 제목"));commitRow->addWidget(title_,1);auto *commit=new QPushButton(tr("원격 커밋 만들기"));commit->setObjectName("ssh_commit");commitRow->addWidget(commit);writes_.append(commit);body->addLayout(commitRow);description_=new QPlainTextEdit;description_->setMaximumHeight(65);description_->setPlaceholderText(tr("원격 커밋 상세 설명"));body->addWidget(description_);controls_.append(title_);controls_.append(description_);connect(commit,&QPushButton::clicked,this,[this]{mutate("commit",{{"message",title_->text()+"\n\n"+description_->toPlainText()}});});
    auto *historyButton=new QPushButton(tr("원격 커밋 기록 · 최근 100개"));body->addWidget(historyButton);controls_.append(historyButton);connect(historyButton,&QPushButton::clicked,this,[this]{send({{"action","history"}},[this](bool ok,const QJsonObject &result,const QString &){if(ok)history_->replace(HistoryWidget::parseLog(QByteArray::fromBase64(result.value("data").toString().toLatin1())));});});
    history_=new HistoryTable;history_->setObjectName("sshHistory");history_->setHorizontalHeaderLabels({tr("그래프"),tr("커밋 메시지"),tr("브랜치 / 태그"),tr("작성자"),tr("날짜"),tr("상세 설명"),"SHA",tr("이메일"),tr("부모 커밋"),tr("기록 시각")});history_->hideColumn(0);history_->setColumnWidth(1,300);history_->setSelectionBehavior(QAbstractItemView::SelectRows);body->addWidget(history_,1);
    status_=new QLabel(tr("연결되지 않음 · 키 또는 ssh-agent로 인증합니다. 비밀번호는 저장하지 않습니다."));status_->setWordWrap(true);status_->setTextFormat(Qt::PlainText);layout->addWidget(status_);
    log_=new QPlainTextEdit;log_->setReadOnly(true);log_->setMaximumHeight(80);log_->setMaximumBlockCount(500);layout->addWidget(log_);
    auto *bottom=new QHBoxLayout;layout->addLayout(bottom);auto *recover=new QPushButton(tr("중단된 helper 기록 확인 · 해제"));bottom->addWidget(recover);controls_.append(recover);connect(recover,&QPushButton::clicked,this,[this]{mutate("acknowledge");});cancel_=new QPushButton(tr("SSH 연결 종료"));bottom->addWidget(cancel_);connect(cancel_,&QPushButton::clicked,this,[this]{if(executor_.writing()&&!confirm(this,tr("SSH 연결 종료"),tr("연결을 끊어도 원격 쓰기는 계속될 수 있습니다. 재연결 후 결과를 확인해야 합니다. 전송을 종료할까요?")))return;executor_.disconnectTransport();online_=false;state_={};update();});auto *close=new QPushButton(tr("닫기"));bottom->addWidget(close);connect(close,&QPushButton::clicked,this,&QDialog::close);
    controls_.append(profiles_);connect(&executor_,&SshExecutor::busyChanged,this,&SshWorkspace::update);connect(&executor_,&SshExecutor::activity,status_,&QLabel::setText);
    auto invalidate=[this]{online_=false;state_={};update();};for(auto *w:{host_,user_,root_,key_})connect(w,&QLineEdit::textEdited,this,invalidate);connect(port_,&QSpinBox::valueChanged,this,invalidate);connect(path_,&QLineEdit::textEdited,this,[this]{state_={};update();});
    connect(profiles_,&QComboBox::currentIndexChanged,this,[this]{online_=false;state_={};auto p=SshProfile::fromJson(profiles_->currentData().toJsonObject());alias_->setText(p.alias);host_->setText(p.host);user_->setText(p.user);key_->setText(p.identity);root_->setText(p.root.isEmpty()?"/home":p.root);port_->setValue(p.port);path_->setText(root_->text());files_->clear();folders_->clear();history_->replace({});repositories();update();});loadProfiles();update();
}
SshProfile SshWorkspace::profile()const{auto p=SshProfile::fromJson(profiles_->currentData().toJsonObject());p.alias=alias_->text();p.host=host_->text().trimmed();p.user=user_->text().trimmed();p.identity=key_->text().trimmed();p.root=root_->text().trimmed();p.port=port_->value();return p;}
void SshWorkspace::loadProfiles(){profiles_->clear();SshProfile fresh;fresh.id=QUuid::createUuid().toString(QUuid::Id128);fresh.root="/home";profiles_->addItem(tr("새 SSH 프로필"),fresh.json());for(const auto &value:savedArray("ssh/profiles")){auto p=SshProfile::fromJson(value.toObject());profiles_->addItem(p.alias.isEmpty()?p.user+"@"+p.host:p.alias,p.json());}profiles_->setCurrentIndex(0);}
void SshWorkspace::saveProfile(){auto p=profile();if(!p.valid()){status_->setText(tr("프로필 입력을 확인하세요. 호스트·사용자·포트와 절대 시작 경로가 필요합니다."));return;}auto all=savedArray("ssh/profiles");bool found=false;for(int i=0;i<all.size();++i)if(all[i].toObject().value("id")==p.id){const auto old=SshProfile::fromJson(all[i].toObject());if(old.host!=p.host||old.port!=p.port){p.id=QUuid::createUuid().toString(QUuid::Id128);break;}all[i]=p.json();found=true;break;}if(!found)all.append(p.json());saveArray("ssh/profiles",all);loadProfiles();for(int i=1;i<profiles_->count();++i)if(profiles_->itemData(i).toJsonObject().value("id")==p.id){profiles_->setCurrentIndex(i);break;}status_->setText(tr("SSH 프로필을 저장했습니다."));}
void SshWorkspace::connectHost(){if(!discardDraft())return;const auto previousPath=path_->text();fetchId_.clear();saveProfile();const auto p=profile();if(!p.valid())return;if(previousPath==p.root||previousPath.startsWith(p.root+"/"))path_->setText(previousPath);
    auto probe=[this,p]{executor_.request(p,{{"action","probe"}},[this,p](bool ok,const QJsonObject &value,const QString &error){const auto match=QRegularExpression("(\\d+)\\.(\\d+)").match(value.value("git").toString());const bool version=match.hasMatch()&&(match.captured(1).toInt()>2||(match.captured(1).toInt()==2&&match.captured(2).toInt()>=31));const auto python=value.value("python").toArray();const bool supportedPython=python.size()>=2&&(python[0].toInt()>3||(python[0].toInt()==3&&python[1].toInt()>=8));online_=ok&&value.value("os")=="posix"&&version&&supportedPython;connectedId_=online_?p.id:QString();state_={};status_->setText(!ok?error:online_?tr("연결됨 · %1 · OS 사용자 %2 · %3 · HOME %4\nGit 인증은 원격 서버의 키/credential helper를 사용합니다. agent forwarding은 꺼져 있습니다.").arg(value.value("platform").toString(),value.value("user").toString(),value.value("git").toString(),value.value("home").toString()):tr("지원하지 않는 서버입니다. POSIX와 Git 2.31 이상이 필요합니다."));update();});};
    if(executor_.trusted(p)){probe();return;}
    executor_.scan(p,[this,p,probe](bool ok,const QJsonObject &value,const QString &error){if(!ok){status_->setText(error);return;}if(!confirm(this,tr("SSH 호스트 키 확인"),tr("%1:%2\n%3\n\n서버 관리자 등 별도 경로로 확인한 지문과 일치하는지 확인하세요. 네트워크에서 읽은 키만으로 서버 신원을 보장할 수 없습니다. 이 키를 신뢰할까요?").arg(p.host).arg(p.port).arg(value.value("fingerprint").toString())))return;QString saveError;if(!executor_.trust(p,value.value("key").toString(),&saveError)){status_->setText(saveError);return;}probe();});
}
void SshWorkspace::send(QJsonObject request,SshExecutor::Callback callback){if(!online_||connectedId_!=profile().id){status_->setText(tr("먼저 해당 SSH 프로필에 연결하세요."));return;}request.insert("repository",path_->text());const auto action=request.value("action").toString();log_->appendPlainText("SSH: "+profile().alias+" · "+action);executor_.request(profile(),request,[this,callback,action](bool ok,const QJsonObject &value,const QString &error){if(!ok){if(value.value("transport_failed").toBool())online_=false;fetchId_.clear();status_->setText(error);state_={};log_->appendPlainText(Diagnostics::redact(error));}else if(!QStringList{"status","read","diff","history","browse"}.contains(action))status_->setText(Diagnostics::redact(value.value("message").toString()));callback(ok,value,error);update();});}
void SshWorkspace::browse(){if(!discardDraft())return;state_={};send({{"action","browse"}},[this](bool ok,const QJsonObject &value,const QString &){if(!ok)return;folders_->clear();for(const auto &entry:value.value("directories").toArray()){auto *item=new QListWidgetItem(entry.toObject().value("name").toString(),folders_);item->setData(Qt::UserRole,entry.toObject().value("path"));}status_->setText(tr("현재 경로: %1 · Git 저장소 루트: %2").arg(value.value("path").toString(),value.value("is_repository").toBool()?tr("예"):tr("아니요")));});}
void SshWorkspace::refresh(){send({{"action","status"}},[this](bool ok,const QJsonObject &value,const QString &){if(!ok)return;state_=value;path_->setText(value.value("repository").toString());files_->clear();for(const auto &entry:value.value("files").toArray()){const auto file=entry.toObject();auto *item=new QListWidgetItem(file.value("status").toString()+"  "+file.value("path").toString(),files_);item->setData(Qt::UserRole,file);item->setCheckState(Qt::Unchecked);}branches_->clear();for(const auto &branch:value.value("branches").toArray())branches_->addItem(branch.toString());branches_->setCurrentText(value.value("branch").toString());status_->setText(Diagnostics::redact(tr("SSH 작성자: %1\n원격 Git 연결: %2\n진행 작업: %3 · 잠금: %4 · helper 기록: %5").arg(value.value("author").toString(),value.value("remotes").toString(),QString::fromUtf8(QJsonDocument(value.value("pending").toArray()).toJson(QJsonDocument::Compact)),QString::fromUtf8(QJsonDocument(value.value("locks").toArray()).toJson(QJsonDocument::Compact)),QString::fromUtf8(QJsonDocument(QJsonObject{{"active",value.value("active")},{"last",value.value("last_operation")}}).toJson(QJsonDocument::Compact)))));remember();});}
void SshWorkspace::mutate(const QString &action,QJsonObject request){if(state_.isEmpty()||executor_.busy())return;if(action=="save"&&(editRepository_!=path_->text()||editProfile_!=profile().id))return;if(action!="save"&&!discardDraft())return;
    if(action=="commit"&&title_->text().trimmed().isEmpty()){status_->setText(tr("커밋 제목을 입력하세요."));return;}
    QJsonArray paths;for(int i=0;i<files_->count();++i)if(files_->item(i)->checkState()==Qt::Checked)paths.append(files_->item(i)->data(Qt::UserRole).toJsonObject().value("path"));request.insert("paths",paths);request.insert("action",action);request.insert("expected",state_.value("fingerprint"));
    if(!confirm(this,tr("SSH 원격 작업 확인"),tr("실행 위치: SSH %1 (%2@%3:%4)\n원격 저장소: %5\n작업: %6\n선택 파일: %7\n\n이 원격 컴퓨터에 변경을 적용할까요? 커밋은 Stage 전체를 포함합니다. 연결 중단은 되돌리기가 아닙니다.").arg(profile().alias,profile().user,profile().host).arg(profile().port).arg(path_->text(),action,QString::fromUtf8(QJsonDocument(paths).toJson(QJsonDocument::Compact)))+"\n"+request.value("branch").toString()+"\n"+request.value("path").toString()+"\n"+request.value("message").toString()))return;
    send(request,[this,action](bool ok,const QJsonObject &value,const QString &){fetchId_=ok&&action=="fetch"?value.value("fetch_id").toString():QString();if(ok){if(action=="commit"){title_->clear();description_->clear();}if(action=="save"){editor_->document()->setModified(false);editHash_.clear();}refresh();}});
}
bool SshWorkspace::discardDraft(){if(!editor_->document()->isModified())return true;if(!confirm(this,tr("SSH 파일 편집"),tr("저장하지 않은 원격 파일 편집을 버릴까요?")))return false;editor_->document()->setModified(false);editPath_.clear();editHash_.clear();editor_->clear();return true;}
void SshWorkspace::showFile(bool edit){if(!files_->currentItem()||!discardDraft())return;const auto file=files_->currentItem()->data(Qt::UserRole).toJsonObject();const auto path=file.value("path").toString();const auto state=file.value("status").toString();
    send({{"action",edit?"read":"diff"},{"path",path},{"staged",state.size()==2&&state[0]!=' '&&state[0]!='?'&&state[1]==' '}},[this,path,edit](bool ok,const QJsonObject &value,const QString &){if(!ok)return;auto bytes=QByteArray::fromBase64(value.value("data").toString().toLatin1());diff_->setVisible(!edit);editor_->setVisible(edit);if(edit){editRepository_=path_->text();editProfile_=profile().id;editPath_=path;editHash_=value.value("hash").toString();editBom_=bytes.startsWith(QByteArray::fromHex("efbbbf"));if(editBom_)bytes.remove(0,3);editCrlf_=bytes.contains("\r\n")&&!QByteArray(bytes).replace("\r\n","").contains('\n');editor_->setPlainText(QString::fromUtf8(bytes));editor_->document()->setModified(false);}else diff_->showPatch(bytes);});
}
void SshWorkspace::remember(bool favorite){if(state_.isEmpty())return;auto all=savedArray("ssh/repositories");QJsonObject entry{{"profile",profile().id},{"path",state_.value("repository")},{"common",state_.value("common_dir")},{"name",QFileInfo(path_->text()).fileName()},{"last_used",QDateTime::currentDateTimeUtc().toString(Qt::ISODate)},{"favorite",false}};for(int i=0;i<all.size();++i)if(all[i].toObject().value("profile")==profile().id&&all[i].toObject().value("path")==entry.value("path")&&all[i].toObject().value("common")==entry.value("common")){entry.insert("favorite",all[i].toObject().value("favorite"));all.removeAt(i);break;}if(favorite)entry.insert("favorite",!entry.value("favorite").toBool());all.prepend(entry);saveArray("ssh/repositories",all);repositories();}
void SshWorkspace::repositories(){saved_->clear();const auto all=savedArray("ssh/repositories");for(bool favorite:{true,false})for(const auto &value:all){const auto entry=value.toObject();if(entry.value("profile")!=profile().id||entry.value("favorite").toBool()!=favorite)continue;auto *item=new QListWidgetItem((favorite?"★ ":"")+entry.value("name").toString()+"\n"+entry.value("path").toString(),saved_);item->setData(Qt::UserRole,entry);}}
void SshWorkspace::update(){const bool busy=executor_.busy();for(auto *w:controls_)w->setEnabled(!busy);const bool ready=online_&&!state_.isEmpty()&&!busy&&state_.value("pending").toArray().isEmpty()&&state_.value("locks").toArray().isEmpty()&&state_.value("active").toObject().isEmpty();for(auto *b:writes_)b->setEnabled(ready);branches_->setEnabled(ready);saveFile_->setEnabled(ready&&editRepository_==path_->text()&&editProfile_==profile().id&&!editHash_.isEmpty()&&editor_->document()->isModified());editor_->setReadOnly(busy);cancel_->setEnabled(online_||busy);scope_->setText(tr("SSH: %1 · %2@%3:%4 · %5\n%6").arg(alias_->text(),user_->text(),host_->text()).arg(port_->value()).arg(online_?tr("연결됨"):tr("오프라인"),path_->text()));}
void SshWorkspace::closeEvent(QCloseEvent *event){if(executor_.busy()){status_->setText(tr("SSH 작업 종료를 기다리거나 연결 종료를 먼저 선택하세요."));event->ignore();return;}if(!discardDraft()){event->ignore();return;}event->accept();}
void SshWorkspace::reject(){if(executor_.busy()){status_->setText(tr("SSH 작업 종료를 기다리거나 연결 종료를 먼저 선택하세요."));return;}if(discardDraft())QDialog::reject();}
